[project]
name = "knowledge_base_app"
version = "0.1.0"
description = "Knowledge base app"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi[standard]>=0.115.12",
    "uvicorn>=0.34.2",
]

[dependency-groups]
dev = [
    "ruff>=0.11.12",
]
